# Site settings
title: Tom Zellner
email: tom.zellner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Website of Tom Zellner <br>
  Full Stack Web Developer with a Passion for Creativity <br>
  Please Feel Free to Contact Me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tomzellner.github.io" # the base hostname & protocol for your site
# twitter_username: tomzellner
github_username:  tomzellner
linkedin_username: mtzellner
facebook_username: ztommyz

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/blogs/page:num/"